### ISSUE TITLE
Create TariHash API / trait

### ISSUE THREAD

**Issue by hansieodendaal** [tari-project/tari-crypto#100]
``` rust
            let mut data = b"TARI CRYPTO NUMS BASEPOINT LABEL - ".to_vec(); // Domain label
            data.append(&mut i.to_le_bytes().to_vec()); // Append domain separated label counter
            let hashed_v = Sha512::digest(&*data);
```

Let's create a ticket to put this into a TariHash API / trait, so that 
a) This is a one-liner
b) No-one can forget to do this (by leveraging the type system)

It's a biggish refactor, so out of scope of this PR - but an important TODO

_Originally posted by @CjS77 in https://github.com/tari-project/tari-crypto/pull/99#discussion_r883561258_

**Comment by CjS77** [comment]
Closed by #106
