### ISSUE TITLE
Zeroize guarantee

### ISSUE THREAD

**Issue by therustmonk** [tari-project/tari-crypto#115]
`Zeroize` is a third-party function that is never called automatically:

```rust
use zeroize::Zeroize;

#[derive(Clone, Copy)]
struct Scalar {
    bytes: [u8; 32],
}

impl Zeroize for Scalar {
    fn zeroize(&mut self) {
        panic!("zeroize called");
    }
}

fn main() {
    let scalar = Scalar {
        bytes: [1; 32],
    };
    let vec_of_scalars: Vec<Scalar> = vec![scalar];
    drop(vec_of_scalars);
    panic!("zeroize never called");
}
```

I've imitated `Scalar` struct from https://doc.dalek.rs/curve25519_dalek/scalar/struct.Scalar.html . The code gives the result:

```
    Finished dev [unoptimized + debuginfo] target(s) in 0.34s
     Running `target/debug/zeroize-check`
thread 'main' panicked at 'zeroize never called', src/main.rs:20:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

That means the places where we use `Vec<Scalar>` will never be zeroized, because it's impossible to:
- override `Drop` method of `Vec` (`zeroize` crate can't do that)
- have both `Copy` and `Drop` (`zeroize` reasonable preferred `Copy`)

To guarantee that all data cleared we have to add a special wrapper will be doing this and require to use it for sensitive data.

Some implementation ideas here: https://github.com/tari-project/tari-crypto/pull/114

For example, we could add the struct that will be used instead of `Vec<Scalar>`:
```rust
pub struct Secrets(GuardedSecret<Vec<Scalar>>);

impl Guarded for Secrets {}
```

**Comment by stringhandler** [comment]
Maybe it's worth looking at this crate:
https://docs.rs/secrecy/latest/secrecy/

**Comment by hansieodendaal** [comment]
Nice test case, did not realize this at all

**Comment by AaronFeickert** [comment]
Is it possible to test if this still occurs with vectors when using the `#[zeroize(drop)]` attribute with `#[derive(Zeroize)]`? This change is made in [PR 137](https://github.com/tari-project/tari-crypto/pull/137) to the `RistrettoSecretKey` struct.

Additionally, I tested the use of a `Zeroizing<Vec<Scalar>>` wrapper with the test code, and it calls `zeroize` as expected. So that's an option.

**Comment by CjS77** [comment]
Also see #147

**Comment by AaronFeickert** [comment]
Can this be closed?
