### ISSUE TITLE
Broken `wasm` tests on `tari`

### ISSUE THREAD

**Issue by AaronFeickert** [tari-project/tari-crypto#142]
[PR 134](https://github.com/tari-project/tari-crypto/pull/134) breaks `wasm` tests on the `tari` repository. Reverting the commit from that PR appears to solve the problem.

**Comment by sdbondi** [comment]
Looks like the tari_crypto/wasm feature is missing from key manager.
`base_layer/key_manager/Cargo.toml`

```diff
- wasm = ["wasm-bindgen", "js", "tari_common_types", "console_error_panic_hook"]
+ wasm = ["tari_crypto/wasm", "wasm-bindgen", "js", "tari_common_types", "console_error_panic_hook"]
```
