### ISSUE TITLE
Blake2 dep is outdated, updating it has some issues to fix 

### ISSUE THREAD

**Issue by delta1** [tari-project/tari-crypto#34]
Blake2 0.8.1 relies on crypto-mac 0.7.0 > generic-array 0.12.3 which has the following rust-sec advisory: 

https://rustsec.org/advisories/RUSTSEC-2020-0146.html 

Bumping to Blake2 0.9.1 leads to some compilation issues to be fixed. Will take a look when I can. 

Context: tari-project/tari#2714

**Comment by CjS77** [comment]
Fixed in #49
