### ISSUE TITLE
Add covering unit tests for files in src/ffi

### ISSUE THREAD

**Issue by mikethetike** [tari-project/tari-crypto#42]
The code in the `src/ffi` has no covering unit tests

I'm using the coverage tool in Idea to determine this, so it may be incorrect, but from my inspection, there are none.
![image](https://user-images.githubusercontent.com/4200336/121501130-38a29080-c9df-11eb-8e9b-38eb5e17b249.png)

**Comment by CjS77** [comment]
Fixed in #44
